bankapp:
  property: bank app profile devs
spring:
  data:
    mongodb:
      uri: mongodb://ludwin:.@localhost:27017/admin
logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.mongodb.driver.protocol.command: DEBUG

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

application:
  name: appbank-microservice

server:
  port: 8081


resilience4j:
  circuitbreaker:
    instances:
      consumptionCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 2000ms
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        maxWaitDurationInHalfOpenState: 5s
        eventConsumerBufferSize: 10
        ignoreExceptions:
          - java.io.IOException

      paymentsCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 2000ms
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        maxWaitDurationInHalfOpenState: 5s
        eventConsumerBufferSize: 10
        ignoreExceptions:
          - java.io.IOException

      movementsCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 2000ms
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        maxWaitDurationInHalfOpenState: 5s
        eventConsumerBufferSize: 10
        ignoreExceptions:
          - java.io.IOException

  timelimiter:
    instances:
      consumptionCircuitBreaker:
        timeoutDuration: 2s
      paymentsCircuitBreaker:
        timeoutDuration: 2s
      movementsCircuitBreaker:
        timeoutDuration: 2s

