bankapp:
  property: bank app profile devs
spring:
  data:
    mongodb:
      uri: mongodb://ludwin:ludwin25@localhost:27017/admin
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

application:
  name: appbank-microservice

server:
  port: 8081