bankapp:
  property: bank app profile devs
spring:
  data:
    mongodb:
      uri: mongodb://ludwin:.@localhost:27017/admin
#      uri: mongodb+srv://lsuarein:s2nhIgSWzlfLLw6F@bankapp.c7xeo.mongodb.net/?retryWrites=true&w=majority&appName=BankApp

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

application:
  name: appbank-microservice

server:
  port: 8081