movements:
  property: bank app movements profile devs
spring:
  data:
    mongodb:
      uri: mongodb://ludwin:.@localhost:27017/admin

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8082