bankapp:
  property: wallet digital profile dev
spring:
  data:
    mongodb:
      uri: mongodb://ludwin:.@localhost:27017/wallet_digital
      autoIndexCreation: true

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8083

